### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by Aananda-giri** [Aananda-giri/ioee#1]
# To Do list
**# How to?**
- choose one topic and ask is anyone working in that topic, if yes we can always collaborate else we can start learning/researching and building
- [ ] ioe_images gallery front_end_improve
- [ ] one to one messenging front-end (normal_messages like messenger/discord)
- [ ] one to one messenging back-end (between random people online)
- [ ] group messenging front-end
- [ ] one to one messenging back-end
- [ ] gropu messenging back-end
- [ ] upload_posts front-end
- [ ] upload_posts back-end
- [ ] ioe_notifications + news front-end  (upload, view, classify & review)
- [ ] ioe_notifications + news back-end  (upload, view, classify & review)
- [ ] file sharing front-end
- [ ] file sharing back_end (torrenting)
